# Generated by Django 3.1.2 on 2020-10-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_type_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceSale',
            field=models.IntegerField(default=0, verbose_name='PriceSale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ecom Name'),
        ),
        migrations.CreateModel(
            name='Sale_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ecom Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('priceSale', models.IntegerField(default=0, verbose_name='PriceSale')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.type')),
            ],
        ),
    ]
