# Generated by Django 3.1.2 on 2020-10-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20201028_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale_Product',
        ),
    ]
