# Generated by Django 3.1.2 on 2020-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.TextField(default='', verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(default=4, verbose_name='ram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ssd',
            field=models.IntegerField(default=0, verbose_name='ssd'),
        ),
    ]
