# Generated by Django 3.1.2 on 2020-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20201119_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.TextField(default='', verbose_name='cpu'),
        ),
    ]
