# Generated by Django 3.1.2 on 2020-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20201119_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ho ten', models.CharField(max_length=200)),
                ('Dia chi', models.CharField(max_length=200)),
                ('Dien thoai', models.CharField(max_length=11)),
            ],
        ),
    ]
