# Generated by Django 3.1.2 on 2020-12-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_auto_20201125_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.TextField(verbose_name='Voucher')),
                ('voucherValue', models.IntegerField(verbose_name='VoucherValue')),
            ],
        ),
    ]
