# Generated by Django 3.1.2 on 2020-12-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucherValue',
            field=models.IntegerField(default=0, verbose_name='VoucherValue'),
        ),
    ]
