# Generated by Django 3.1.2 on 2020-12-05 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_auto_20201205_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Thoi gian giao hang',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 20, 52, 52, 143874)),
        ),
        migrations.AddField(
            model_name='user',
            name='Tong thanh toan',
            field=models.IntegerField(default=0),
        ),
    ]
