# Generated by Django 3.1.2 on 2020-12-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_auto_20201205_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Dia chi',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Dien thoai',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tong thanh toan',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Ho ten',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Thoi gian giao hang',
        ),
        migrations.AddField(
            model_name='user',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 20, 59, 18, 443149)),
        ),
    ]
