# Generated by Django 3.1.2 on 2020-12-05 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_auto_20201205_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Time',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 21, 6, 27, 724057)),
        ),
    ]
