# Generated by Django 3.1.2 on 2020-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_auto_20201205_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Time',
            field=models.CharField(max_length=200),
        ),
    ]
